[profile.default]
src = "src"
out = "out"
libs = ["../pseudo-arbitrage-amm/lib"]

solc_version = "0.8.30"
evm_version = "cancun"

optimizer = true
optimizer_runs = 200

via_ir = true

remappings = [
    "@openzeppelin/=../pseudo-arbitrage-amm/lib/openzeppelin-contracts/",
    "forge-std/=../pseudo-arbitrage-amm/lib/forge-std/src/",
    "swap-vm/=../pseudo-arbitrage-amm/lib/swap-vm/src/"
]

